### PR TITLE
0.8.0 + removed patch merged by upstream

### PR DESCRIPTION
**Pull request by CasualRascal**
Version 0.4.90 would fail to build
Updated to 0.8.0
Upstream fixed source code to [here](https://github.com/AyatanaIndicators/ayatana-ido/commit/033c9f49dbb70842094ca89017ab58faf9540bb9) so I removed the patch

### CODE REVIEW

**Comment by CasualRascal** [comment]
I forgot to mention I also fixed the Source0 link

**Comment by AngryPenguinPL** [comment]
Looks good to me, let's see if it builds correctly, previous 0.5.0 was broken, thats why I not commit it.
Thanks.

**Comment by AngryPenguinPL** [comment]
Looks like you forgot to upload your new source and edit the .abf.yml file.

Also source url need fix or rather restore the previous version of the link that was possible to the download.

**Comment by CasualRascal** [comment]
Sorry, I did not compile with abf at all and didn't upload source there.
What's with the url? Does the #/ break something?

**Pull request merged**
